# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: michael.ryan.zengel@cern.ch
author_name: Michael Zengel
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_ext_test_apod
project_short_description: Show a random NASA Astronomy Picture of the Day in a JupyterLab
    panel
python_name: jupyterlab_ext_test_apod
repository: https://github.com/vre-hub/zenodo-jupyterlab-extension/extension_tutorial.git
test: true

