name: "Setup"
runs:
  using: "composite"
  steps:
    # - name: Install Node
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '20.x'

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true

    - name: Testing conda env in separate job
      run: |
        conda deactivate
        conda info --envs
      shell: bash -l {0}

    - name: Create and activate conda environment
      run: |
          conda config --set always_yes yes --set changeps1 no
          conda init bash
          source ~/.bashrc
          conda create -n jupyterlab-ext --override-channels --strict-channel-priority -c conda-forge -c nodefaults jupyterlab=4 nodejs=20 git copier=9 jinja2-time
          conda info --envs
          conda activate jupyterlab-ext
          conda info --envs
      shell: bash -l {0}

    - name: Verify Node.js Installation
      run: |
        source ~/.bashrc
        conda activate jupyterlab-ext
        node -v
        npm -v
      shell: bash

    - name: Clearing cache to ensure correct yarn usage
      run: |
        rm -rf node_modules
        rm -rf .yarn/cache
      shell: bash

    - name: Install yarn
      run: |
        source ~/.bashrc
        conda activate jupyterlab-ext
        npm install yarn
        npm list
        npm list yarn
        echo $PATH
        which yarn
        conda list yarn
        pwd
        ls -a
        yarn --version
      shell: bash

    - name: Verify yarn installation
      run: |
        source ~/.bashrc
        conda activate jupyterlab-ext
        yarn --version
      shell: bash
    
    # - name: Running Yarn Build
    #   run: |
    #     yarn run build
    #   shell: bash