name: "Setup"
runs:
  using: "composite"
  steps:
    # - name: Install Node
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: '20.x'

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true

    - name: Setup Node
      run: |
        conda install -y -c conda-forge nodejs=20
      shell: bash

    - name: Verify Node.js Installation
      run: |
        node -v
        npm -v
      shell: bash

    # - name: Install JupyterLab
    #   run: |


    # - name: Install environmental variables
    #   run: |
    #     pip install -v .
    #   shell: bash

    - name: Clearing cache to ensure correct yarn usage
      run: |
        rm -rf node_modules
        rm -rf .yarn/cache
      shell: bash

    - name: Install yarn
      run: |
        conda install yarn
      shell: bash

    - name: Verify yarn installation
      run: |
        yarn --version
      shell: bash
    
    # - name: Running Yarn Build
    #   run: |
    #     yarn run build
    #   shell: bash