name: "Setup"
runs:
  using: "composite"
  steps:
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Verify Node.js Installation
      run: |
        node -v
        npm -v
      shell: bash

    # - name: Install JupyterLab
    #   run: |


    # - name: Install environmental variables
    #   run: |
    #     pip install -v .
    #   shell: bash

    - name: Install yarn
      run: |
        conda install yarn
      shell: bash

    - name: Verify yarn installation
      run: |
        yarn --version
      shell: bash
    
    # - name: Running Yarn Build
    #   run: |
    #     yarn run build
    #   shell: bash