# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: michael.ryan.zengel@cern.ch
author_name: Michael Zengel
has_binder: true
has_settings: false
kind: frontend
labextension_name: zenodo_jupyterlab
project_short_description: A JupyterLab extension.
python_name: zenodo_jupyterlab
repository: ''
test: true

