title: "Zenodo Jupyter Lab Extension"
description: "Documentation for VRE Hub Zenodo Jupyter Lab Extension"
remote_theme: pmarsceill/just-the-docs
color_scheme: dark

# Table of contents
nav:
  - title: "Home"
    url: /
    nav_order: 1

  - title: "Install"
    url: /install/
    nav_order: 2
    children:
      - title: "For Users"
        url: /install/#users
        nav_order: 1
      - title: "For Developpers"
        url: /install/#developers
        nav_order: 2

  - title: "Frontend Usage"
    url: /usage/
    nav_order: 3