name: Build extension

on:
  push:
    branches: master
  pull_request:
    branches: '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -uses: .github/actions/Setup.yaml