name: Build and install extension

on:
  push:
    branches: main
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # cache: 'yarn'
      
      - name: Install yarn
        run: |
          npm install -g corepack
          corepack enable
          yarn -v

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: 'x64'

      - name: Setup pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-3.11-${{ hashFiles('package.json') }}
          restore-keys: |
            pip-3.11-
            pip-

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt
        shell: bash

      - name: Install JS dependencies
        run: yarn install
        shell: bash

  install_extension:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: |
          set -eux
          python -m pip install zenodo-jupyterlab
